public class Bioinf1 {
    //counts the appearance of a string
    public static void main(String[] args) {
        String text = "GGGGGCGTCAGAGTGGTCCAGAGTGTGGCAGAGTGCTCCAGAGTGACTCGCAGAGTGGCAGAGTGGCAGAGTGACAGAGTGGGGTGCAGCAGAGTGAACAGAGTGCCCAGAGTGACGCAGAGTGTCAGAGTGCTCTAATCCCTTCAGAGTGCGACAGAGTGCAGAGTGTATCAGAGTGTCTCAACCAGAGTGGCCAAACAGAGTGCGCGCTATGTTAAAGATACATGTCAGAGTGCGGCCCCTTCAGAGTGTCAGAGTGCCAGAGTGCAATCAGAGTGCACGACAGAGTGCATTTTCAGAGTGCTCAGAGTGGGGCACAGAGTGCGCAGAGTGCAGAGTGTAATCCAGAGTGCAGAGTGAGACCAGAGTGCCAAATTGGCGAATGTCAGAGTGTACCAGAGTGAAGCAACAGAGTGTTCAGAGTGTTACAGAGTGTCAGAGTGATCAGAGTGAATAACAGAGTGCTGAGACAGAGTGCAGAGTGCAGAGTGGCATCAGAGTGCAGAGTGTACAGAGTGGGTCAGAGTGTCCAGAGTGTCAGAGTGACAGAGTGGCAGAGTGCAGAGTGTTGCAGAGTGACAGAGTGCAGAGTGACAGAGTGCAGAGTGTTCCAGAGTGGAATGCTCCGCAGAGTGTTGCGACCAGAGTGCACAGGACAGAGTGCAGAGTGCAGAGTGGTTTTCCTGCAGAGTGCGACAGAGTGCGCTCAGAGTGGGCAGAGTGACAGAGTGTGCAGAGTGCAGAGTGAGGTCAGAGTGCCAGAGTGAACAGAGTGCCAGAGTGATGTGCAGAGTGACCTCCAGAGTGAGCCAGAGTGGTCACAGAGTGCAGAGTGGCAGAGTGTTAGCCAGAGTGGCATCAGAGTGCAGAGTGCAGTCGACACCAACAGAGTGTCTGTGGCAGAGTGCGCTAATACTAGGCAGAGTGACAGAGTGCATGGCAGAGTGCTCCAGAGTGG";
        String pattern = "CAGAGTGCA";
        int count1 = 0;


        for (int indexes = 0; indexes < text.length(); indexes++) {

            if (pattern.length() + indexes <= text.length()) {
                String name = text.substring(indexes, pattern.length() + indexes).intern();

                if (name == pattern) {
                    count1++;
                }
            }
        }
        System.out.println(count1);
    }
}